services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dental_db
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      # 'db' es el nombre del servicio de arriba, Docker lo resuelve como la IP
      DATABASE_URL: postgres://postgres:postgres@db:5432/dental_db?sslmode=disable
      PORT: 8080
    depends_on:
      - db